<a href="https://colab.research.google.com/github/Animichael/Animated-Login-Page/blob/main/numpy_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy library
import numpy as np

In [ ]:
# How to creat a numpy array using list

a =[1,2,3,4,5]
arr=np.array(a)
type(arr)

numpy.ndarray

In [ ]:
b = (10, 20, 30, 40,50)
np.array(b)

array([10, 20, 30, 40, 50])

In [ ]:
# How to create array oof zeros in numpy

np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(50, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# generate arrays of ones

np.ones(50, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [ ]:
# how to create ann empty numpy array using empty()
np.empty(1)

array([5.e-324])

In [ ]:
# How to generate numbers using arange in numpy

np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(2, 51, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
# linespace()
np.linspace(1,  10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
numbers = [1,6,7,9,45,67,78,23,78,90,45,1,2,4,6]
arr2 =np.array(numbers)
np.sort(arr2)

array([ 1,  1,  2,  4,  6,  6,  7,  9, 23, 45, 45, 67, 78, 78, 90])

In [ ]:
# How to concatenate two numpy arrays into a single array
x=np.array([10,20,30,40,50,60,70])
y=np.array([80,90,100,110,120,130,140])
np.concatenate((x,y))


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [ ]:
# How to retrieve value from a numpy array using the index method
x[0]

10

In [ ]:
# How to retrieve values from a numpy array using the slicing technique
x[0:5]

array([10, 20, 30, 40, 50])

In [ ]:
# How to chaeck for the number of items in your numpy array

print(np.size(x))
len(x)

7


7

In [ ]:
# How to use the shape method in numpy

np.shape(x)

(7,)

In [ ]:
# Operatins with array

x= np.arange(1, 21)
x_array =np.array(x)
print(x_array)
print()

y =x_array *2
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# How to create a multi dimensional array in numoy

multi_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11,12,13,14,15]])
val = np.array ( [1, 2, 3, 4, 5])

In [ ]:
contents = [[],[],[]]

In [ ]:
print(val.shape)
print(multi_array.shape)

(5,)
(3, 5)


In [ ]:
print('The values are', multi_array[0][3], multi_array[1][3], multi_array[2][3])

The values are 4 9 14
The values are 4 9 14


In [ ]:
# np.vstack

a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])


In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
#how to use reshape method in numpy

values =np.arange(1,21)
np.array(values)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
values.reshape(2,10)
values.reshape(10,2)
values.reshape(4,5)
values.reshape(5,4)
values.reshape(1,20)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [ ]:
np.random.rand(20)

array([0.54512763, 0.45991029, 0.37640682, 0.82344632, 0.55488206,
       0.61540411, 0.82900378, 0.03661466, 0.10384193, 0.52401789,
       0.46596154, 0.92605348, 0.47179685, 0.86355447, 0.27985313,
       0.46129184, 0.72111608, 0.34428007, 0.6343304 , 0.04168766])

In [ ]:
values.round(2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

AttributeError: 'numpy.ndarray' object has no attribute 'asarray'